### ISSUE TITLE
Broken link to linked open vocabularies

### ISSUE THREAD

**Issue by caro401** [tropy/docs#8]
https://github.com/tropy/docs/blob/181113fc81dbdd224e59dda07fec04cf83e9223c/before-you-begin/metadata.md?plain=1#L28 as seen on https://docs.tropy.org/before-you-begin/metadata

The link for "linked open vocabularies" (http://lov.okfn.org/dataset/lov/) on this page doesn't appear to be active any more, and no longer redirects to the correct site. I think https://lov.linkeddata.es/dataset/lov is the equivalent working link.

Happy to submit a PR for this, unless this will cause problems for the documentation generator

**Comment by inukshuk** [comment]
Good catch, thanks! PRs are always welcome of course!
